## Subgrounds Tutorials: Lido Exploration


This code demonstrates how to use the Subgrounds library to interact with a specific subgraph, in this case, the Lido Ethereum subgraph, and fetch usage metrics for a given period (last 30 days).

1. Import the necessary libraries: The code begins by importing the required Python libraries, including `datetime` from the standard library, and `SyntheticField` and `Subgrounds` from the `subgrounds` library. It also imports `pandas` for handling data as DataFrames.
   
2. Initialize Subgrounds: The `Subgrounds` object is initialized as `sg`. This object serves as the main entry point for interacting with different subgraphs and fetching data using GraphQL queries.
   
3. Load Lido Ethereum subgraph: The Lido Ethereum subgraph is loaded using its API URL. This returns a `Subgraph` object named `lido_activity`, which is used to interact with the Lido Ethereum subgraph.
   
4. Query usage metrics daily snapshots: The code constructs a query to fetch the `usageMetricsDailySnapshots` entity from the Lido Ethereum subgraph. It specifies ordering options to sort the data by timestamp in descending order and limits the number of results to 30, effectively fetching the last 30 days of data.
   
5. Create a SyntheticField for human-readable timestamps: A `SyntheticField` named `datetime` is created for the `UsageMetricsDailySnapshot` entity. This field takes the original `timestamp` field, converts it to a human-readable format using the `datetime.fromtimestamp()` function, and stores it as a float. This makes it easier to read and understand the timestamp data.
   
6. Fetch data and store it in a DataFrame: The `sg.query_df()` function is used to execute the query and fetch the data. It takes a list of the fields to be fetched (timestamp, daily active users, cumulative unique users, and daily transaction count) and returns a pandas DataFrame containing the data.

The primary focus of this code is to demonstrate how the Subgrounds library can be used to interact with a subgraph (Lido Ethereum subgraph) and fetch specific data using queries. This data can then be processed, manipulated, and analyzed using other Python libraries like pandas.

In [1]:
from datetime import datetime
from subgrounds.subgraph import SyntheticField
from subgrounds import Subgrounds
import pandas as pd

# Initialize Subgrounds
sg = Subgrounds()

# Load a subgraph using its API URL
lido_activity = sg.load_subgraph('https://api.thegraph.com/subgraphs/name/messari/lido-ethereum')

# Create a FieldPath object for the required fields in the financialsDailySnapshots entity.
# Specify options to sort the data by timestamp in descending order and limit the number of results to 30.
usage_daily_snapshot_30days = lido_activity.Query.usageMetricsDailySnapshots(
    orderBy=lido_activity.UsageMetricsDailySnapshot.timestamp, 
    orderDirection='desc', 
    first=30
)

# Create a SyntheticField on the Swap entity called `timestamp`, which will format the timestamp field into something more human readable
lido_activity.UsageMetricsDailySnapshot.datetime = SyntheticField(
  lambda timestamp: str(datetime.fromtimestamp(timestamp)),
  SyntheticField.FLOAT,
  lido_activity.UsageMetricsDailySnapshot.timestamp
)

sg.query_df([
    usage_daily_snapshot_30days.datetime,
    usage_daily_snapshot_30days.dailyActiveUsers,
    usage_daily_snapshot_30days.cumulativeUniqueUsers,
    usage_daily_snapshot_30days.dailyTransactionCount
])

,usageMetricsDailySnapshots_datetime,usageMetricsDailySnapshots_dailyActiveUsers,usageMetricsDailySnapshots_cumulativeUniqueUsers,usageMetricsDailySnapshots_dailyTransactionCount
0,2023-03-16 11:36:23,243,131967,290
1,2023-03-15 18:52:59,348,131829,426
2,2023-03-14 18:59:47,388,131620,484
3,2023-03-13 18:51:23,248,131370,335
4,2023-03-12 18:55:35,461,131224,568
5,2023-03-11 17:57:35,286,130969,326
6,2023-03-10 17:58:35,380,130808,478
7,2023-03-09 17:58:23,275,130641,402
8,2023-03-08 17:40:35,278,130496,362
9,2023-03-07 17:58:23,263,130329,351
10,2023-03-06 17:58:59,277,130163,420
11,2023-03-05 17:54:47,375,130012,567
12,2023-03-04 17:54:11,381,129786,529
13,2023-03-03 17:58:11,360,129551,517
14,2023-03-02 17:59:47,346,129371,539
15,2023-03-01 17:58:11,324,129156,432
16,2023-02-28 17:56:59,378,128980,671
17,2023-02-27 17:59:11,393,128747,565
18,2023-02-26 17:52:11,422,128496,684
19,2023-02-25 17:56:23,341,128223,544
20,2023-02-24 17:53:59,386,128028,519
21,2023-02-23 17:55:23,419,127793,503
22,2023-02-22 17:53:35,378,127506,464
23,2023-02-21 17:57:47,432,127280,512
24,2023-02-20 17:56:47,721,127033,850
25,2023-02-19 17:59:35,1284,126599,1498
26,2023-02-18 17:58:59,1358,125807,1529
27,2023-02-17 17:58:35,2981,124967,3173
28,2023-02-16 17:59:23,840,123530,935
29,2023-02-15 17:59:59,334,123137,430