## Subgrounds Tutorials: RocketPool  x Lido Exploration

This code demonstrates how to use the Subgrounds library to analyze and compare revenue and usage data for two DeFi protocols, Lido and Rocket Pool. The Subgrounds library provides an easy-to-use interface to fetch and manipulate data from The Graph, a decentralized protocol for indexing and querying data from blockchains like Ethereum.


In the code, we first import the necessary libraries, such as `Subgrounds`, `SyntheticField`, `datetime`, and `panda`s. We then initialize a `Subground`s instance, which is used to interact with subgraphs from The Graph. We load the Lido and Rocket Pool subgraphs using their API URLs by calling the `load_subgraph` method. This allows us to query data from these subgraphs easily. 


For protocol `revenue analysis`, we query the `financials daily snapshots` for both protocols and fetch the latest snapshot to compare the `cumulative supply-side`, `protocol-side`, and `total revenue`. We store the comparison in a pandas DataFrame and print it out. 


For protocol usage analysis, we query the usage metrics daily snapshots for both protocols and fetch the data for the past 30 days. We convert the timestamp field to a human-readable format using the `apply` method on the pandas DataFrame. We then calculate the daily and hourly transaction counts and active user counts for both protocols, store the results in DataFrames, and print them out.


 Throughout the code, Subgrounds is used to load subgraphs, query data from the subgraphs, and fetch the queried data in pandas DataFrames, making it easy to manipulate and analyze the data.

In [1]:
from subgrounds import Subgrounds
from subgrounds.subgraph import SyntheticField
from datetime import datetime
import pandas as pd

# Initialize Subgrounds
sg = Subgrounds()

# Load subgraphs for Lido and rocketPool
lido_subgraph = sg.load_subgraph('https://api.thegraph.com/subgraphs/name/messari/lido-ethereum')
rocketPool_subgraph = sg.load_subgraph('https://api.thegraph.com/subgraphs/name/messari/rocket-pool-ethereum')

# Query financials daily snapshots for both protocols (sorted by timestamp)
lido_financials = lido_subgraph.Query.financialsDailySnapshots(orderBy=lido_subgraph.FinancialsDailySnapshot.timestamp, orderDirection='desc')
rocketPool_financials = rocketPool_subgraph.Query.financialsDailySnapshots(orderBy=rocketPool_subgraph.FinancialsDailySnapshot.timestamp, orderDirection='desc')

# Fetch the latest financials snapshot for both protocols
lido_financials_latest = sg.query_df([
    lido_financials.cumulativeSupplySideRevenueUSD, 
    lido_financials.cumulativeProtocolSideRevenueUSD, 
    lido_financials.cumulativeTotalRevenueUSD]).iloc[0]
    
rocketPool_financials_latest = sg.query_df([
    rocketPool_financials.cumulativeSupplySideRevenueUSD, 
    rocketPool_financials.cumulativeProtocolSideRevenueUSD, 
    rocketPool_financials.cumulativeTotalRevenueUSD]).iloc[0]

# Compare cumulative supply-side, protocol-side, and total revenue for both protocols
revenue_comparison = pd.DataFrame({'Lido': lido_financials_latest, 'rocketPool': rocketPool_financials_latest})
print(revenue_comparison)

                                                            Lido    rocketPool
financialsDailySnapshots_cumulativeSupplySideRe...  4.985835e+08  9.456642e+06
financialsDailySnapshots_cumulativeProtocolSide...  5.616937e+07  1.576503e+06
financialsDailySnapshots_cumulativeTotalRevenueUSD  5.547529e+08  1.103315e+07

## Subgrounds Tutorials: RocketPool  x Lido Exploration - Continued

This code uses the Subgrounds library to interact with the Lido and Rocket Pool subgraphs and fetch usage metrics daily snapshots for both protocols over the past 30 days. Here's a step-by-step explanation of the code:


- Import required libraries: Subgrounds, SyntheticField, datetime, and pandas.
Initialize Subgrounds with sg = Subgrounds().

- Load Lido and Rocket Pool subgraphs using their respThis code uses the Subgrounds library to interact with the Lido and Rocket Pool subgraphs and fetch usage metrics daily snapshots for both protocols over the past 30 days. Here's a step-by-step explanation of the code:

- Import required libraries: Subgrounds, SyntheticField, datetime, and pandas.

- Initialize Subgrounds with `sg = Subgrounds()`.

- Load Lido and Rocket Pool subgraphs using their respective API URLs.

- Query the usage metrics daily snapshots for both protocols, ordering by timestamp in descending order, and limit the results to the last 30 days.

- Fetch the usage metrics for the past 30 days for both protocols by querying the daily timestamp, daily transaction count, and daily active users.

- Combine the results from both protocols into two separate DataFrames: `lido_usage_30` and `rocket_pool_usage_30`.

The code also includes commented-out sections for styling the DataFrames and displaying them in a more visually appealing format. To use this functionality, you can uncomment the sections that define the `style_dataframe` function, format the timestamps in the DataFrames, and style and display the resulting DataFrames.

In [2]:
from subgrounds import Subgrounds
from subgrounds.subgraph import SyntheticField
from datetime import datetime
import pandas as pd

# Initialize Subgrounds
sg = Subgrounds()

# Load subgraphs for Lido and rocketPool_subgraph
lido_subgraph = sg.load_subgraph('https://api.thegraph.com/subgraphs/name/messari/lido-ethereum')
rocketPool_subgraph = sg.load_subgraph('https://api.thegraph.com/subgraphs/name/messari/rocket-pool-ethereum')

# Query usage metrics daily snapshots for both protocols (sorted by timestamp)
lido_usage = lido_subgraph.Query.usageMetricsDailySnapshots(
    orderBy=lido_subgraph.UsageMetricsDailySnapshot.timestamp,
    orderDirection='desc',
    first=30)

rocket_pool_usage = rocketPool_subgraph.Query.usageMetricsDailySnapshots(
    orderBy=rocketPool_subgraph.UsageMetricsDailySnapshot.timestamp, 
    orderDirection='desc',
    first=30)

# Fetch usage metrics for the past 30 days for both protocols
lido_usage_30days = sg.query_df([
    lido_usage.timestamp,
    lido_usage.dailyTransactionCount, 
    lido_usage.dailyActiveUsers])
    
rocket_pool_usage_30days = sg.query_df([
    rocket_pool_usage.timestamp,
    rocket_pool_usage.dailyTransactionCount, 
    rocket_pool_usage.dailyActiveUsers])


[lido_usage_30,rocket_pool_usage_30] = sg.query_df([
    lido_usage.timestamp, 
    lido_usage.dailyTransactionCount, 
    lido_usage.dailyActiveUsers,
    rocket_pool_usage.timestamp,
    rocket_pool_usage.dailyTransactionCount, 
    rocket_pool_usage.dailyActiveUsers
])
rocket_pool_usage_30

,usageMetricsDailySnapshots_timestamp,usageMetricsDailySnapshots_dailyTransactionCount,usageMetricsDailySnapshots_dailyActiveUsers
0,1678984583,290,243
1,1678924379,426,348
2,1678838387,484,388
3,1678751483,335,248
4,1678665335,568,461
5,1678579055,326,286
6,1678492715,478,380
7,1678406303,402,275
8,1678318835,362,278
9,1678233503,351,263
10,1678147139,420,277
11,1678060487,567,375
12,1677974051,529,381
13,1677887891,517,360
14,1677801587,539,346
15,1677715091,432,324
16,1677628619,671,378
17,1677542351,565,393
18,1677455531,684,422
19,1677369383,544,341
20,1677282839,519,386
21,1677196523,503,419
22,1677110015,464,378
23,1677023867,512,432
24,1676937407,850,721
25,1676851175,1498,1284
26,1676764739,1529,1358
27,1676678315,3173,2981
28,1676591963,935,840
29,1676505599,430,334

In [3]:
lido_usage_30

,usageMetricsDailySnapshots_timestamp,usageMetricsDailySnapshots_dailyTransactionCount,usageMetricsDailySnapshots_dailyActiveUsers
0,1678984583,290,243
1,1678924379,426,348
2,1678838387,484,388
3,1678751483,335,248
4,1678665335,568,461
5,1678579055,326,286
6,1678492715,478,380
7,1678406303,402,275
8,1678318835,362,278
9,1678233503,351,263
10,1678147139,420,277
11,1678060487,567,375
12,1677974051,529,381
13,1677887891,517,360
14,1677801587,539,346
15,1677715091,432,324
16,1677628619,671,378
17,1677542351,565,393
18,1677455531,684,422
19,1677369383,544,341
20,1677282839,519,386
21,1677196523,503,419
22,1677110015,464,378
23,1677023867,512,432
24,1676937407,850,721
25,1676851175,1498,1284
26,1676764739,1529,1358
27,1676678315,3173,2981
28,1676591963,935,840
29,1676505599,430,334